MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_mpvit_fpn_backbone"
  MPVIT:
    NAME: "mpvit_base"
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    NORM: "SyncBN"
    DROP_PATH: 0.1
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  ANCHOR_GENERATOR:
    SIZES: [[4], [8], [16], [32], [64]] 
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 3000
    POST_NMS_TOPK_TEST: 1500
  ROI_HEADS:
    NUM_CLASSES: 4
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    SCORE_THRESH_TEST: 0.3
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_train",)
SOLVER:
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  IMS_PER_BATCH: 8
  STEPS: (60000, 80000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 50000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 1000
DATALOADER:
  REPEAT_THRESHOLD: 0.05
  SAMPLER_TRAIN: RepeatFactorTrainingSampler
VERSION: 2
